/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sign_ip;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hp 1
 */
public class Forgotpass extends javax.swing.JFrame {

    /**
     * Creates new form Forgotpass
     */
    public Forgotpass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        f_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        f_name = new javax.swing.JTextField();
        f_phone = new javax.swing.JTextField();
        f_age = new javax.swing.JTextField();
        f_roll = new javax.swing.JTextField();
        f_net_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        f_address = new javax.swing.JTextField();
        f_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(115, 100));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 40));

        f_id.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        getContentPane().add(f_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 360, 40));

        jLabel3.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FULL NAME :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 170, 40));

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMAIL ID: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 40));

        jLabel5.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 170, 40));

        jLabel6.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ROLL NO :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 40));

        jLabel8.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AGE :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 90, 30));

        jLabel11.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("UPDATE FORM");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 260, 40));

        jLabel9.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PHONE NO: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 150, 40));

        f_name.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        getContentPane().add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 330, 40));

        f_phone.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        f_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_phoneActionPerformed(evt);
            }
        });
        getContentPane().add(f_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 330, 40));

        f_age.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        getContentPane().add(f_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 110, 30));

        f_roll.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        f_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_rollActionPerformed(evt);
            }
        });
        getContentPane().add(f_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, 30));

        f_net_id.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        f_net_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_net_idActionPerformed(evt);
            }
        });
        getContentPane().add(f_net_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 360, 40));

        jButton1.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 210, 40));

        jButton2.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 210, 40));

        jLabel10.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ADDRESS :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 40));

        f_address.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        getContentPane().add(f_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 920, 40));

        f_pass.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        getContentPane().add(f_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 330, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/gif-wallpaper-13.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_rollActionPerformed

    private void f_net_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_net_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_net_idActionPerformed

    private void f_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_phoneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login m=new login();
        m.setVisible(true);
        setVisible(false);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ID=f_id.getText();
        String ROLL_NO=f_roll.getText();
        String EMAIL_ID=f_net_id.getText();
        String PHONE_NO=f_phone.getText();
        String ADDRESS=f_address.getText();
        String AGE=f_age.getText();
        String FULL_NAME=f_name.getText();
        String PASSWORD = f_pass.getText();
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            PreparedStatement ps;
            if(PASSWORD.length()>8)
            {
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","chup");
                if(ID!=null|| ROLL_NO!=null ||FULL_NAME!=null|| AGE!=null||PHONE_NO!=null|| EMAIL_ID!=null|| PASSWORD!=null|| ADDRESS!=null){
                    ps = con.prepareStatement("UPDATE STUDENTS SET ROLL_NO='"+ROLL_NO+"',AGE='"+AGE+"',PHONE_NO='"+PHONE_NO+"',EMAIL_ID='"+EMAIL_ID+"',PASSWORD='"+PASSWORD+"',ADDRESS='"+ADDRESS+"' WHERE ID="+ID+"");
                    ps.executeQuery();
                    ps.close();
                    con.close();
                } else{
                    JOptionPane.showMessageDialog(null,"Some feild is Missing here ? Check Please...");
                }
            
            wel_come w = new wel_come();
            w.setVisible(true);
            setVisible(false);
            dispose();
            }
            else{
                    JOptionPane.showMessageDialog(null,"Password Must be more than 8 characters.");
            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f_address;
    private javax.swing.JTextField f_age;
    private javax.swing.JTextField f_id;
    private javax.swing.JTextField f_name;
    private javax.swing.JTextField f_net_id;
    private javax.swing.JPasswordField f_pass;
    private javax.swing.JTextField f_phone;
    private javax.swing.JTextField f_roll;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
 byte[] pimage = null;
}
