/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sign_ip;
import java.awt.HeadlessException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.lang.Exception;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import sign_ip.work;


/**
 *
 * @author rr
 */
public class login extends javax.swing.JFrame {
    //Connection con=null;
    
 ResultSet rs=null;
 String person_image=null;
 //PreparedStatement ps=null;
  public login(){
      
        initComponents();
         
  }

    /**
     * Creates new form login
     */
    
        
  //    initComponents();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jj = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        L_PASS = new javax.swing.JPasswordField();
        L_ID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        course = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mobile = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        age = new javax.swing.JTextField();
        id_d = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jj, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 30, 20));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_PASS.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jPanel1.add(L_PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 320, 30));

        L_ID.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jPanel1.add(L_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 320, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setText("NAME or ID:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setText("PASSWORD:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("LOGIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, 140, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("LOGIN INTO YOUR ACCOUNT HERE PLEASE....");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1180, 70));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1280, 260));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("COLLEGE:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 20));

        jLabel18.setText("ROLL:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, 20));

        jLabel27.setText("ID:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, 20));

        jLabel24.setText("ADDRESS:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, 20));

        jLabel23.setText("EMAIL ID:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, 20));

        jLabel20.setText("MOBILE:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 20));

        jLabel16.setText("NAME:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 20));

        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        jPanel3.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 230, 20));

        jLabel25.setText("(+91)");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, 20));
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 230, 20));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 230, 20));
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 230, 20));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 300, 40));

        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        jPanel3.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 190, 20));

        jLabel28.setText("PASSWORD:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, 20));
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 90, 20));

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel3.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 90, 20));

        id_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_dActionPerformed(evt);
            }
        });
        jPanel3.add(id_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 90, 20));

        jLabel17.setText("AGE:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 20));

        jLabel5.setText("* Click The Button Below....");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, 170, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/Mario-PNG-Image.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 310, 450));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 90, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("NEW USER HERE");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 310, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 680, 420));

        jLabel29.setText("ROLL:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, 20));

        jLabel30.setText("COLLEGE:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, 20));

        jLabel31.setText("ID:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, 20));

        jPanel4.setBackground(new java.awt.Color(204, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jButton4.setText("?");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 140, 120));

        jLabel3.setText("YOUR PASSWORD and also for");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 170, 10));

        jLabel4.setText("UPDATE your DETAILS.");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 20));

        jLabel2.setText("* CLICK here when you forgot ");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/forgot-password-cartoon.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 400, 330));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 490, 420));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/button_cancel.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, 30, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_dActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ID=id_d.getText();
        String ROLL_NO=jTextField1.getText();
        String FULL_NAME = name.getText();
        String AGE=age.getText();
        String COURSE=course.getText();
        String PHONE_NO= mobile.getText();
        String EMAIL_ID=email.getText();
        String PASSWORD=pass.getText();
        String ADDRESS=address.getText();
         
       try
        {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                PreparedStatement ps;
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","chup");
                if(ID != null && PASSWORD!= null && PASSWORD.length()>=8 && PHONE_NO.length()>=10){
                    ps = con.prepareStatement("INSERT INTO STUDENTS(ID,ROLL_NO,FULL_NAME,AGE,COURSE,PHONE_NO,EMAIL_ID,PASSWORD,ADDRESS) VALUES('"+ID+"','"+ROLL_NO+"','"+FULL_NAME+"','"+AGE+"','"+COURSE+"','"+PHONE_NO+"','"+EMAIL_ID+"','"+PASSWORD+"','"+ADDRESS+"')");
                    ps.executeQuery();
                    JOptionPane.showMessageDialog(null, "Registration Successful ! Have a Good Day.");
                    wel_come e=new wel_come();
                    e.setVisible(true);
                    
                    ps.close();
                    con.close();
                } else{
                    JOptionPane.showMessageDialog(null,"Invalid Information Check your Password and mobile Number.");
                }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, " ~ oHh ~ "+e+" ~ OhH ~ ");

        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String ID= L_ID.getText();
        String ID_2 = null;
        String PASS = L_PASS.getText();
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            PreparedStatement ps;

            
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","chup");
                
                    ps =(OraclePreparedStatement) con.prepareStatement("select * from STUDENTS where ID='"+ID+"' AND PASSWORD='"+PASS+"'");

                    rs = ps.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "! You Successfully Logged In !");
                        work h = new work();
                        h.setVisible(true);
                        ps.close(); con.close();
                        setVisible(false);
                        dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, " ! EMAIL OR PASSWORD IS INCORRECT !");
                    }
                
            

        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Forgotpass f = new Forgotpass();
        f.setVisible(true);
        setVisible(false); dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {  public void run() { new login().setVisible(true); } });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField L_ID;
    private javax.swing.JPasswordField L_PASS;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField course;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id_d;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jj;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
String filename= null;
    int s=0;
    byte[] pimage = null;
}